class ListOfTypes {
  static const List<String> hareketTipi = [
    "Mal ve Hizmet Alınır ve Satılır",
    "Mal ve Hizmet Sadece Satılır",
    "Mal ve Hizmet Sadece Alınır",
    "Sadece Parasal Hareket Yapılır",
    "Cari Hareket Yapılmaz"
  ];
  static const List<String> baglantiTipi = [
    "Müşteri",
    "Satıcı",
    "Diğer Cari",
    "Dağıtıcı",
    "Bayi",
    "Hedef Müşteri",
    "Hedef Bayi",
    "Alt Bayi",
    "Bağlı Ortaklık"
  ];
  static const List<String> stokAlimCinsi = [
    "Toptan ve Perakende",
    "Toptan",
    "Perakende"
  ];
  static const List<String> stokSatimCinsi = [
    "Toptan ve Perakende",
    "Toptan",
    "Perakende"
  ];
  static const List<String> cariOdemeSekli = [
    "Vadeye göre",
    "Satış üzerinden",
  ];
  static const List<String> cariEfaturaCinsi = [
    "Temel Fatura",
    "Ticari Fatura",
    "Yolcu Beraberinde Fatura",
    "İhracat",
  ];
  static const List<String> isk1 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
  ];
  static const List<String> isk2 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> isk3 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> isk4 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> isk5 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
    "4. İskontodan Yüzde",
    "4. İskonto Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> isk6 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
    "4. İskontodan Yüzde",
    "4. İskonto Sonrası Ara Toplamdan Yüzde",
    "5. İskontodan Yüzde",
    "5. İskonto Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> mas1 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
    "4. İskontodan Yüzde",
    "4. İskonto Sonrası Ara Toplamdan Yüzde",
    "5. İskontodan Yüzde",
    "5. İskonto Sonrası Ara Toplamdan Yüzde",
    "6. İskontodan Yüzde",
    "6. İskonto Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> mas2 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
    "4. İskontodan Yüzde",
    "4. İskonto Sonrası Ara Toplamdan Yüzde",
    "5. İskontodan Yüzde",
    "5. İskonto Sonrası Ara Toplamdan Yüzde",
    "6. İskontodan Yüzde",
    "6. İskonto Sonrası Ara Toplamdan Yüzde",
    "1. Masraftan Yüzde",
    "1. Masraf Sonrası Ara Toplamdan Yüzde",
  ];

  static const List<String> mas3 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
    "4. İskontodan Yüzde",
    "4. İskonto Sonrası Ara Toplamdan Yüzde",
    "5. İskontodan Yüzde",
    "5. İskonto Sonrası Ara Toplamdan Yüzde",
    "6. İskontodan Yüzde",
    "6. İskonto Sonrası Ara Toplamdan Yüzde",
    "1. Masraftan Yüzde",
    "1. Masraf Sonrası Ara Toplamdan Yüzde",
    "2. Masraftan Yüzde",
    "2. Masraf Sonrası Ara Toplamdan Yüzde",
  ];
  static const List<String> mas4 = [
    "Brüt Toplamdan Yüzde",
    "Önceki Ara Toplamdan Yüzde",
    "Tutar",
    "Ana Miktar * Tutar",
    "Miktar 2 * Tutar",
    "Miktar 3 * Tutar",
    "Bedelsiz Miktar",
    "1. İskontodan Yüzde",
    "1. İskonto Sonrası Ara Toplamdan Yüzde",
    "2. İskontodan Yüzde",
    "2. İskonto Sonrası Ara Toplamdan Yüzde",
    "3. İskontodan Yüzde",
    "3. İskonto Sonrası Ara Toplamdan Yüzde",
    "4. İskontodan Yüzde",
    "4. İskonto Sonrası Ara Toplamdan Yüzde",
    "5. İskontodan Yüzde",
    "5. İskonto Sonrası Ara Toplamdan Yüzde",
    "6. İskontodan Yüzde",
    "6. İskonto Sonrası Ara Toplamdan Yüzde",
    "1. Masraftan Yüzde",
    "1. Masraf Sonrası Ara Toplamdan Yüzde",
    "2. Masraftan Yüzde",
    "2. Masraf Sonrası Ara Toplamdan Yüzde",
    "3. Masraftan Yüzde",
    "3. Masraf Sonrası Ara Toplamdan Yüzde",
  ];
}
